version: 0.2

phases:
  install:
    commands:
      - echo Installing app
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code
  post_build:
    commands:
      - echo Build completed on `date`